
puts "-- Loading countries"
Country.where(code: 'af').first_or_create!
Country.where(code: 'al').first_or_create!
Country.where(code: 'aq').first_or_create!
Country.where(code: 'dz').first_or_create!
Country.where(code: 'as').first_or_create!
Country.where(code: 'ad').first_or_create!
Country.where(code: 'ao').first_or_create!
Country.where(code: 'ag').first_or_create!
Country.where(code: 'az').first_or_create!
Country.where(code: 'ar').first_or_create!
Country.where(code: 'au').first_or_create!
Country.where(code: 'at').first_or_create!
Country.where(code: 'bs').first_or_create!
Country.where(code: 'bh').first_or_create!
Country.where(code: 'bd').first_or_create!
Country.where(code: 'am').first_or_create!
Country.where(code: 'bb').first_or_create!
Country.where(code: 'be').first_or_create!
Country.where(code: 'bm').first_or_create!
Country.where(code: 'bt').first_or_create!
Country.where(code: 'bo').first_or_create!
Country.where(code: 'ba').first_or_create!
Country.where(code: 'bw').first_or_create!
Country.where(code: 'bv').first_or_create!
Country.where(code: 'br').first_or_create!
Country.where(code: 'bz').first_or_create!
Country.where(code: 'io').first_or_create!
Country.where(code: 'sb').first_or_create!
Country.where(code: 'vg').first_or_create!
Country.where(code: 'bn').first_or_create!
Country.where(code: 'bg').first_or_create!
Country.where(code: 'mm').first_or_create!
Country.where(code: 'bi').first_or_create!
Country.where(code: 'by').first_or_create!
Country.where(code: 'kh').first_or_create!
Country.where(code: 'cm').first_or_create!
Country.where(code: 'ca').first_or_create!
Country.where(code: 'cv').first_or_create!
Country.where(code: 'ky').first_or_create!
Country.where(code: 'cf').first_or_create!
Country.where(code: 'lk').first_or_create!
Country.where(code: 'td').first_or_create!
Country.where(code: 'cl').first_or_create!
Country.where(code: 'cn').first_or_create!
Country.where(code: 'tw').first_or_create!
Country.where(code: 'cx').first_or_create!
Country.where(code: 'cc').first_or_create!
Country.where(code: 'co').first_or_create!
Country.where(code: 'km').first_or_create!
Country.where(code: 'yt').first_or_create!
Country.where(code: 'cg').first_or_create!
Country.where(code: 'cd').first_or_create!
Country.where(code: 'ck').first_or_create!
Country.where(code: 'cr').first_or_create!
Country.where(code: 'hr').first_or_create!
Country.where(code: 'cu').first_or_create!
Country.where(code: 'cy').first_or_create!
Country.where(code: 'cz').first_or_create!
Country.where(code: 'bj').first_or_create!
Country.where(code: 'dk').first_or_create!
Country.where(code: 'dm').first_or_create!
Country.where(code: 'do').first_or_create!
Country.where(code: 'ec').first_or_create!
Country.where(code: 'sv').first_or_create!
Country.where(code: 'gq').first_or_create!
Country.where(code: 'et').first_or_create!
Country.where(code: 'er').first_or_create!
Country.where(code: 'ee').first_or_create!
Country.where(code: 'fo').first_or_create!
Country.where(code: 'fk').first_or_create!
Country.where(code: 'gs').first_or_create!
Country.where(code: 'fj').first_or_create!
Country.where(code: 'fi').first_or_create!
Country.where(code: 'ax').first_or_create!
Country.where(code: 'fr').first_or_create!
Country.where(code: 'gf').first_or_create!
Country.where(code: 'pf').first_or_create!
Country.where(code: 'tf').first_or_create!
Country.where(code: 'dj').first_or_create!
Country.where(code: 'ga').first_or_create!
Country.where(code: 'ge').first_or_create!
Country.where(code: 'gm').first_or_create!
Country.where(code: 'ps').first_or_create!
Country.where(code: 'de').first_or_create!
Country.where(code: 'gh').first_or_create!
Country.where(code: 'gi').first_or_create!
Country.where(code: 'ki').first_or_create!
Country.where(code: 'gr').first_or_create!
Country.where(code: 'gl').first_or_create!
Country.where(code: 'gd').first_or_create!
Country.where(code: 'gp').first_or_create!
Country.where(code: 'gu').first_or_create!
Country.where(code: 'gt').first_or_create!
Country.where(code: 'gn').first_or_create!
Country.where(code: 'gy').first_or_create!
Country.where(code: 'ht').first_or_create!
Country.where(code: 'hm').first_or_create!
Country.where(code: 'va').first_or_create!
Country.where(code: 'hn').first_or_create!
Country.where(code: 'hk').first_or_create!
Country.where(code: 'hu').first_or_create!
Country.where(code: 'is').first_or_create!
Country.where(code: 'in').first_or_create!
Country.where(code: 'id').first_or_create!
Country.where(code: 'ir').first_or_create!
Country.where(code: 'iq').first_or_create!
Country.where(code: 'ie').first_or_create!
Country.where(code: 'il').first_or_create!
Country.where(code: 'it').first_or_create!
Country.where(code: 'ci').first_or_create!
Country.where(code: 'jm').first_or_create!
Country.where(code: 'jp').first_or_create!
Country.where(code: 'kz').first_or_create!
Country.where(code: 'jo').first_or_create!
Country.where(code: 'ke').first_or_create!
Country.where(code: 'kp').first_or_create!
Country.where(code: 'kr').first_or_create!
Country.where(code: 'kw').first_or_create!
Country.where(code: 'kg').first_or_create!
Country.where(code: 'la').first_or_create!
Country.where(code: 'lb').first_or_create!
Country.where(code: 'ls').first_or_create!
Country.where(code: 'lv').first_or_create!
Country.where(code: 'lr').first_or_create!
Country.where(code: 'ly').first_or_create!
Country.where(code: 'li').first_or_create!
Country.where(code: 'lt').first_or_create!
Country.where(code: 'lu').first_or_create!
Country.where(code: 'mo').first_or_create!
Country.where(code: 'mg').first_or_create!
Country.where(code: 'mw').first_or_create!
Country.where(code: 'my').first_or_create!
Country.where(code: 'mv').first_or_create!
Country.where(code: 'ml').first_or_create!
Country.where(code: 'mt').first_or_create!
Country.where(code: 'mq').first_or_create!
Country.where(code: 'mr').first_or_create!
Country.where(code: 'mu').first_or_create!
Country.where(code: 'mx').first_or_create!
Country.where(code: 'mc').first_or_create!
Country.where(code: 'mn').first_or_create!
Country.where(code: 'md').first_or_create!
Country.where(code: 'me').first_or_create!
Country.where(code: 'ms').first_or_create!
Country.where(code: 'ma').first_or_create!
Country.where(code: 'mz').first_or_create!
Country.where(code: 'om').first_or_create!
Country.where(code: 'na').first_or_create!
Country.where(code: 'nr').first_or_create!
Country.where(code: 'np').first_or_create!
Country.where(code: 'nl').first_or_create!
Country.where(code: 'an').first_or_create!
Country.where(code: 'aw').first_or_create!
Country.where(code: 'nc').first_or_create!
Country.where(code: 'vu').first_or_create!
Country.where(code: 'nz').first_or_create!
Country.where(code: 'ni').first_or_create!
Country.where(code: 'ne').first_or_create!
Country.where(code: 'ng').first_or_create!
Country.where(code: 'nu').first_or_create!
Country.where(code: 'nf').first_or_create!
Country.where(code: 'no').first_or_create!
Country.where(code: 'mp').first_or_create!
Country.where(code: 'um').first_or_create!
Country.where(code: 'fm').first_or_create!
Country.where(code: 'mh').first_or_create!
Country.where(code: 'pw').first_or_create!
Country.where(code: 'pk').first_or_create!
Country.where(code: 'pa').first_or_create!
Country.where(code: 'pg').first_or_create!
Country.where(code: 'py').first_or_create!
Country.where(code: 'pe').first_or_create!
Country.where(code: 'ph').first_or_create!
Country.where(code: 'pn').first_or_create!
Country.where(code: 'pl').first_or_create!
Country.where(code: 'pt').first_or_create!
Country.where(code: 'gw').first_or_create!
Country.where(code: 'tl').first_or_create!
Country.where(code: 'pr').first_or_create!
Country.where(code: 'qa').first_or_create!
Country.where(code: 're').first_or_create!
Country.where(code: 'ro').first_or_create!
Country.where(code: 'ru').first_or_create!
Country.where(code: 'rw').first_or_create!
Country.where(code: 'bl').first_or_create!
Country.where(code: 'sh').first_or_create!
Country.where(code: 'kn').first_or_create!
Country.where(code: 'ai').first_or_create!
Country.where(code: 'lc').first_or_create!
Country.where(code: 'mf').first_or_create!
Country.where(code: 'pm').first_or_create!
Country.where(code: 'vc').first_or_create!
Country.where(code: 'sm').first_or_create!
Country.where(code: 'st').first_or_create!
Country.where(code: 'sa').first_or_create!
Country.where(code: 'sn').first_or_create!
Country.where(code: 'rs').first_or_create!
Country.where(code: 'sc').first_or_create!
Country.where(code: 'sl').first_or_create!
Country.where(code: 'sg').first_or_create!
Country.where(code: 'sk').first_or_create!
Country.where(code: 'vn').first_or_create!
Country.where(code: 'si').first_or_create!
Country.where(code: 'so').first_or_create!
Country.where(code: 'za').first_or_create!
Country.where(code: 'zw').first_or_create!
Country.where(code: 'es').first_or_create!
Country.where(code: 'eh').first_or_create!
Country.where(code: 'sd').first_or_create!
Country.where(code: 'sr').first_or_create!
Country.where(code: 'sj').first_or_create!
Country.where(code: 'sz').first_or_create!
Country.where(code: 'se').first_or_create!
Country.where(code: 'ch').first_or_create!
Country.where(code: 'sy').first_or_create!
Country.where(code: 'tj').first_or_create!
Country.where(code: 'th').first_or_create!
Country.where(code: 'tg').first_or_create!
Country.where(code: 'tk').first_or_create!
Country.where(code: 'to').first_or_create!
Country.where(code: 'tt').first_or_create!
Country.where(code: 'ae').first_or_create!
Country.where(code: 'tn').first_or_create!
Country.where(code: 'tr').first_or_create!
Country.where(code: 'tm').first_or_create!
Country.where(code: 'tc').first_or_create!
Country.where(code: 'tv').first_or_create!
Country.where(code: 'ug').first_or_create!
Country.where(code: 'ua').first_or_create!
Country.where(code: 'mk').first_or_create!
Country.where(code: 'eg').first_or_create!
Country.where(code: 'gb').first_or_create!
Country.where(code: 'gg').first_or_create!
Country.where(code: 'je').first_or_create!
Country.where(code: 'im').first_or_create!
Country.where(code: 'tz').first_or_create!
Country.where(code: 'us').first_or_create!
Country.where(code: 'vi').first_or_create!
Country.where(code: 'bf').first_or_create!
Country.where(code: 'uy').first_or_create!
Country.where(code: 'uz').first_or_create!
Country.where(code: 've').first_or_create!
Country.where(code: 'wf').first_or_create!
Country.where(code: 'ws').first_or_create!
Country.where(code: 'ye').first_or_create!
Country.where(code: 'zm').first_or_create!
Country.where(code: 'yu').first_or_create!
Country.where(code: 'cw').first_or_create!
Country.where(code: 'sx').first_or_create!
Country.where(code: 'bq').first_or_create!
puts "-- Finished loading countries"
